version: '3.4'

services:
   clientapp:
    image: ${DOCKER_REGISTRY-}clientapp
    build:
        context: .
        dockerfile: ClientApp/Dockerfile

   gatewayserviceapi:
    image: ${DOCKER_REGISTRY-}gatewayserviceapi
    ports:
      - "80:80"
    build:
        context: .
        dockerfile: GatewayServiceAPI/Dockerfile

   pokedexserviceget:
    container_name: getPokedex
    network_mode: host
    build:
        context: .
        dockerfile: PokedexService/Dockerfile
    environment: 
        VAR1: "get"

   pokedexservicedelete:
     container_name: deletePokedex
     network_mode: host
     build:
        context: .
        dockerfile: PokedexService/Dockerfile
     environment: 
        VAR1: "delete"
       

