version: '3.4'

services:
   clientapp:
    image: ${DOCKER_REGISTRY-}clientapp
    build:
        context: .
        dockerfile: ClientApp/Dockerfile

   gatewayserviceapi:
    image: ${DOCKER_REGISTRY-}gatewayserviceapi
    ports:
      - "80:80"
    build:
        context: .
        dockerfile: GatewayServiceAPI/Dockerfile


   pokedexservice:
    image: ${DOCKER_REGISTRY-}pokedexservice
    network_mode: host
    build:
        context: .
        dockerfile: PokedexService/Dockerfile

